
[build-system]
requires = ["hatchling","hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "InvestCircle"
version = "0.0.1"
description = "InvestCircle : peer-to-peer stock research and community platform"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    # See: https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Programming Language :: Unix Shell",
]
dependencies = ["click"]

[project.urls]
Homepage = "https://github.com/AnirudhPhophalia/InvestCircle"
Issues = "https://github.com/AnirudhPhophalia/InvestCircle/issues"

# Adapted from https://stackoverflow.com/a/50156706
[tool.pytest.ini_options]
pythonpath = [
  "code"
]
# THE END -------------------------------------------
